spring.application.name=spring_REST.API
spring.jpa.packages-to-scan=com.example.spring_REST.API.model.entity

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG